apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: ec-cli-v01-tech-preview
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ec-cli-v01-tech-preview
    app.kubernetes.io/part-of: ec-v01-tech-preview
  name: ec-cli-v01-tech-preview
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: ec-cli-v01-tech-preview
status:
  loadBalancer: {}
